### PR TITLE
Remove deprecated options.app_domain in connection resource

### PR DESCRIPTION
**Pull request by reify-tanner-stirrat**
## Description
Per the code, [app_domain is deprecated](https://github.com/auth0/terraform-provider-auth0/blob/main/auth0/resource_auth0_connection.go#L248-L252). I don't know enough about what `domain` is to be able to add any additional context, though.

## Checklist

**Note:** Checklist required to be completed before a PR is considered to be reviewable.

#### Auth0 Code of Conduct
- [x] I have read and agreed to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

#### Auth0 General Contribution Guidelines
- [x] I have read the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

#### Changes include test coverage?
- [ ] Yes
- [x] Not needed

#### Does the description provide the correct amount of context?
- [x] Yes, the description provides enough context for the reviewer to understand what these changes accomplish

#### Have you updated the documentation?
- [x] Yes, I've updated the appropriate docs
- [ ] Not needed

#### Is this code ready for production?
- [x] Yes, all code changes are intentional and no debugging calls are left over

### CODE REVIEW

**Review by sergiughf — CHANGES_REQUESTED** [review]
Thanks for spotting this @reify-tanner-stirrat, however would you mind removing the app_domain from the resource schema as well and from any other references inside the code? 🙏🏻

**Comment by reify-tanner-stirrat** [comment]
@sergiughf my thought was to only update the references in the docs, rather than actually creating a breaking change by removing `app_domain` from the codebase. Would you prefer that I go ahead and create the breaking change?

**Comment by sergiughf** [comment]
@reify-tanner-stirrat Yep, feel free to go ahead and remove `app_domain`. If you notice closely it's never set within the state anywhere :) It's deprecated and also never used anywhere else inside the codebase.

**Comment by reify-tanner-stirrat** [comment]
Ah, got it. I removed that reference from the code. There are a few more references in test fixtures, but they don't prevent tests from passing.

**Review by sergiughf — APPROVED** [review]
Thanks for the contribution @reify-tanner-stirrat!

**Comment by xanonid** [comment]
For the future, it would be really nice if the plugin supports some backwards-compatibility and can automatically migrate the state if necessary. The breaking changes from #202 and #207 break really the plugin and produce (at least partially) totally confusing error messages. Only the potential dangerous manual editing of the state json or removing+reimporting resources to the state file allows upgrading to the new provider versions - some documentation for manual migration steps (beside linking to the PRs) would have helped.

**Comment by xanonid** [comment]
@sergiughf Don't worry. Thanks for the hint to the release tags. I checked only the CHANGELOG.md which does not contain the recommended migration steps.

**Comment by sergiughf** [comment]
Thanks for spotting that, that's something we missed. I'll make sure we retroactively add it to the project's CHANGELOG.md as well.

**Pull request merged**
