### PR TITLE
ESD-25205: Deprecate enabled_clients on the auth0_connection resource

### PR DESCRIPTION
**Pull request by sergiught**
### 🔧 Changes

The issue surfaced through https://github.com/auth0/terraform-provider-auth0/issues/416 is caused by the fact that we allow for 2 ways of managing `enabled_clients` on 2 separate resources that affect the planning phase of the terraform process. 

This is similar to what we experienced when we had the `auth0_organization.connections` and `auth0_organization_connection` resource, where we ended up keeping just the latter. 

So we're deprecating the use of `enabled_clients` through the `auth0_connection` resource in favor of the `auth0_connection_client` resource.

### 📝 Checklist

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### CODE REVIEW

**Review by Widcket — APPROVED** [review]

**Comment by willvedd** [comment]
**Update: ** Instead of deprecating, we're just opting to remove the problematic field altogether. Either way users will need to migrate to the resource, a breaking change just communicates that in a stronger way than deprecation. Once we've graduated from v0 we'll be more methodical about deprecations and maintaining backwards compatibility.

**Comment by perplexa** [comment]
it would be nice to have some deprecation notice next time for people who are using this provider in production environments.

**Comment by maxime-gaudron** [comment]
@willvedd When will the provider reach v1 tho? it wasn't a great surprise this morning :)

**Comment by roblframpton** [comment]
Does this repo not use semantic versioning?  This breaking change caused us some difficulty when our CI started failing due to the interface change but our local workspaces were fine, and we'd like to avoid that in the future.

**Pull request merged**
