### PR TITLE
GH-860: Update docs for action secrets

### PR DESCRIPTION
**Pull request by sergiught**
### 🔧 Changes

~This PR adds logic to prevent sending actions secret as empty array if none configured within the resource so they can be managed out of bound without erasing them.~

**Update**:
After careful consideration, we ended up just with an update to the docs advising users to not partially manage secrets.

### 📚 References

- #860 

### 📝 Checklist

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### CODE REVIEW

**Review by Widcket — APPROVED** [review]

**Comment by willvedd** [comment]
Does this prevent actions from being deleted? Also, I see that a recording has changed but feel like there should be an accompanying test change.

**Comment by sergiught** [comment]
@willvedd

> Does this prevent actions from being deleted?
Could you help clarify this? As the change we've done here in this PR is simply make sure that if secrets are not presents within the terraform resource block, we don't send `{"secrets": []}`. The recording has been updated to ensure that is the case. 

When flattening we have no way of knowing if the `secrets` attribute was omitted from the payload or if the `secrets` was present as an empty array. Thus, the inability to add a specific test for this, other than ensuring the recording gets updated correctly.

**Comment by willvedd** [comment]
@sergiught I'm curious why we prevent secrets from being an empty array. Can you clarify why that doesn't prevent us from intentionally emptying-out secrets?

**Comment by sergiught** [comment]
@willvedd Happy to. We advertise the `secrets` block as optional https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/action#secrets, but the current behaviour doesn't really match that. When the `secrets` block is not present within the config we wipe out any other secrets that might be found on the action on remote that a user might not want to keep track of within the terraform config. In all other cases when a config parameter is optional we omit it from the payload.

**Review by willvedd — APPROVED** [review]

**Pull request merged**
